# Generated by Django 5.0.1 on 2024-01-31 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_metalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalink',
            name='data_create',
            field=models.DateField(default=datetime.date(2024, 1, 30)),
        ),
    ]
