# Generated by Django 5.0.1 on 2024-01-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_metalink_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalink',
            name='data_create',
            field=models.CharField(default='31/01/2024', max_length=225),
        ),
    ]
