# Generated by Django 5.0.1 on 2024-01-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_metalink_category_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
