# Generated by Django 5.0.1 on 2024-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('is_published', models.BooleanField(default=False, help_text='Este campo precisa estar marcado para a pagina ser exibida publicamente')),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, default=None, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
