# Generated by Django 5.0.1 on 2024-01-30 22:09

import utils.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='text',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='assets/%Y/%m/', validators=[utils.validate.valideta_png]),
        ),
    ]
